### ISSUE TITLE
Target (classic) .NET Framework

### ISSUE THREAD

**Issue by Zweitze** [clintmasden/monday.client#1]
Forcing .NET standard does not work at projects which are forced to stay in .NET Framework.
It is possible to convert by starting a new project, importing sources files and figuring out the dependencies, plus a compiler error - but now I'm missing updates in this library.

The wish is having a package targeting multiple .NET platforms. To see how it's done:
https://weblog.west-wind.com/posts/2017/Jun/22/MultiTargeting-and-Porting-a-NET-Library-to-NET-Core-20

**Comment by clintmasden** [comment]
@Zweitze, I appreciate the link/information, yet I do not plan to update this project since monday depreciated its 1.0 API.  I'd suggest creating a .net library solution and copying this repo's source to fit your needs.

**Comment by Zweitze** [comment]
Ha! I actually used the v2, and the wish should be there. I'll move it there.
On a related note, you may consider to update the link at https://clintmasden.com/monday-client/
It links to this page.

**Comment by clintmasden** [comment]
@Zweitze The link https://clintmasden.com/monday-client/ is correct and relates to v1 only.
